"""Change Attempt

Revision ID: bed459e269cd
Revises: 2591cbbbe1e4
Create Date: 2025-06-16 15:24:56.062409

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bed459e269cd'
down_revision: Union[str, None] = '2591cbbbe1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt', 'time_used_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attempt', 'memory_used_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attempt', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempt', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('attempt', 'memory_used_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attempt', 'time_used_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
